CFLAGS += -I./$(APP_SOURCES_DIR)/driver/mpu6050
CPPFLAGS += -I./$(APP_SOURCES_DIR)/driver/mpu6050

VPATH += $(APP_SOURCES_DIR)/driver/mpu6050

SOURCES += $(APP_SOURCES_DIR)/driver/mpu6050/mpu_6050.c

