CFLAGS		+= -I./$(APP_SOURCES_DIR)/driver/stm32_rtc
CPPFLAGS	+= -I./$(APP_SOURCES_DIR)/driver/stm32_rtc

VPATH += $(APP_SOURCES_DIR)/driver/stm32_rtc
SOURCES_CPP += $(APP_SOURCES_DIR)/driver/stm32_rtc/RTC.cpp

