
CFLAGS		+= -I./$(APP_SOURCES_DIR)/application/Tasks
CPPFLAGS	+= -I./$(APP_SOURCES_DIR)/application/Tasks

VPATH += $(APP_SOURCES_DIR)/application/Tasks

SOURCES_CPP += $(APP_SOURCES_DIR)/application/Tasks/task_button.cpp