CFLAGS += -I./$(BOOTLOADER_SOURCES_DIR)/driver/button
CPPFLAGS += -I./$(BOOTLOADER_SOURCES_DIR)/driver/button

VPATH += $(BOOTLOADER_SOURCES_DIR)/driver/button

SOURCES += $(BOOTLOADER_SOURCES_DIR)/driver/button/button.c
