CFLAGS += -I./$(APP_SOURCES_DIR)/driver/hmc5883l
CPPFLAGS += -I./$(APP_SOURCES_DIR)/driver/hmc5883l

VPATH += $(APP_SOURCES_DIR)/driver/hmc5883l

SOURCES += $(APP_SOURCES_DIR)/driver/hmc5883l/hmc5883l.c

