
CFLAGS		+= -I./$(APP_SOURCES_DIR)/application/Pages
CPPFLAGS	+= -I./$(APP_SOURCES_DIR)/application/Pages

VPATH += $(APP_SOURCES_DIR)/application/Pages

SOURCES_CPP += $(APP_SOURCES_DIR)/application/Pages/page_watch.cpp
SOURCES_CPP += $(APP_SOURCES_DIR)/application/Pages/page_menu.cpp

SOURCES_CPP += $(APP_SOURCES_DIR)/application/Pages/page_timer.cpp
SOURCES_CPP += $(APP_SOURCES_DIR)/application/Pages/page_setting.cpp
SOURCES_CPP += $(APP_SOURCES_DIR)/application/Pages/page_mpu.cpp
SOURCES_CPP += $(APP_SOURCES_DIR)/application/Pages/page_compass.cpp
SOURCES_CPP += $(APP_SOURCES_DIR)/application/Pages/page_runner_game.cpp
SOURCES_CPP += $(APP_SOURCES_DIR)/application/Pages/page_flashing.cpp
SOURCES_CPP += $(APP_SOURCES_DIR)/application/Pages/page_boids.cpp