CFLAGS += -I./$(BOOTLOADER_SOURCES_DIR)/application
CPPFLAGS += -I./$(BOOTLOADER_SOURCES_DIR)/application

VPATH += $(BOOTLOADER_SOURCES_DIR)/application

SOURCES += $(BOOTLOADER_SOURCES_DIR)/application/main.c
SOURCES += $(BOOTLOADER_SOURCES_DIR)/application/usb_descriptors.c
