CFLAGS		+= -I./$(APP_SOURCES_DIR)/Oled_GUI/Inc
CPPFLAGS	+= -I./$(APP_SOURCES_DIR)/Oled_GUI/Inc

CFLAGS		+= -I./$(APP_SOURCES_DIR)/Oled_GUI
CPPFLAGS	+= -I./$(APP_SOURCES_DIR)/Oled_GUI

VPATH += $(APP_SOURCES_DIR)/Oled_GUI/Src
VPATH += $(APP_SOURCES_DIR)/Oled_GUI

SOURCES_CPP += $(APP_SOURCES_DIR)/Oled_GUI/Src/gui.cpp
SOURCES_CPP += $(APP_SOURCES_DIR)/Oled_GUI/Src/gui_port.cpp
SOURCES_CPP += $(APP_SOURCES_DIR)/Oled_GUI/Src/gui_render.cpp
SOURCES_CPP += $(APP_SOURCES_DIR)/Oled_GUI/Src/gui_core.cpp
SOURCES_CPP += $(APP_SOURCES_DIR)/Oled_GUI/Src/gui_anim.cpp

SOURCES_CPP += $(APP_SOURCES_DIR)/Oled_GUI/Src/gui_page_manager.cpp

SOURCES_CPP += $(APP_SOURCES_DIR)/Oled_GUI/Src/gui_group.cpp
SOURCES_CPP += $(APP_SOURCES_DIR)/Oled_GUI/Src/gui_sw.cpp
SOURCES_CPP += $(APP_SOURCES_DIR)/Oled_GUI/Src/gui_check_box.cpp
SOURCES_CPP += $(APP_SOURCES_DIR)/Oled_GUI/Src/gui_free_style.cpp
SOURCES_CPP += $(APP_SOURCES_DIR)/Oled_GUI/Src/gui_label.cpp
SOURCES_CPP += $(APP_SOURCES_DIR)/Oled_GUI/Src/gui_slider.cpp
SOURCES_CPP += $(APP_SOURCES_DIR)/Oled_GUI/Src/gui_bmp.cpp
SOURCES_CPP += $(APP_SOURCES_DIR)/Oled_GUI/Src/gui_idctor.cpp
SOURCES_CPP += $(APP_SOURCES_DIR)/Oled_GUI/Src/gui_popup.cpp

