CFLAGS		+= -I. -I./$(APP_SOURCES_DIR)/AKOS -I./$(APP_SOURCES_DIR)/AKOS/kernel -I./$(APP_SOURCES_DIR)/AKOS/kernel/inc -I./$(APP_SOURCES_DIR)/AKOS/port/arm/cortex-m3
CPPFLAGS	+= -I. -I./$(APP_SOURCES_DIR)/AKOS -I./$(APP_SOURCES_DIR)/AKOS/kernel -I./$(APP_SOURCES_DIR)/AKOS/kernel/inc -I./$(APP_SOURCES_DIR)/AKOS/port/arm/cortex-m3

VPATH += $(APP_SOURCES_DIR)/AKOS/kernel
VPATH += $(APP_SOURCES_DIR)/AKOS/kernel/src
VPATH += $(APP_SOURCES_DIR)/AKOS/port/arm/cortex-m3

SOURCES += $(APP_SOURCES_DIR)/AKOS/kernel/src/core.c
SOURCES += $(APP_SOURCES_DIR)/AKOS/kernel/src/list.c
SOURCES += $(APP_SOURCES_DIR)/AKOS/kernel/src/memory.c
SOURCES += $(APP_SOURCES_DIR)/AKOS/kernel/src/message.c
SOURCES += $(APP_SOURCES_DIR)/AKOS/kernel/src/priority.c
SOURCES += $(APP_SOURCES_DIR)/AKOS/kernel/src/shell.c
SOURCES += $(APP_SOURCES_DIR)/AKOS/kernel/src/thread.c
SOURCES += $(APP_SOURCES_DIR)/AKOS/kernel/src/timer.c
SOURCES += $(APP_SOURCES_DIR)/AKOS/port/arm/cortex-m3/port.c
