include $(APP_SOURCES_DIR)/driver/mpu6050/Makefile
include $(APP_SOURCES_DIR)/driver/hmc5883l/Makefile
include $(APP_SOURCES_DIR)/driver/stm32_rtc/Makefile
include $(APP_SOURCES_DIR)/driver/sh1106/Makefile
include $(APP_SOURCES_DIR)/driver/button/Makefile

