
CFLAGS		+= -I./$(APP_SOURCES_DIR)/platform
CPPFLAGS	+= -I./$(APP_SOURCES_DIR)/platform

VPATH += $(APP_SOURCES_DIR)/platform

SOURCES += $(APP_SOURCES_DIR)/platform/io_cfg.c
SOURCES += $(APP_SOURCES_DIR)/platform/xprintf.c
