CFLAGS += -I./$(BOOTLOADER_SOURCES_DIR)/device/STM32F10x_StdPeriph_Driver/inc
CPPFLAGS += -I./$(BOOTLOADER_SOURCES_DIR)/device/STM32F10x_StdPeriph_Driver/inc

VPATH += $(BOOTLOADER_SOURCES_DIR)/device/STM32F10x_StdPeriph_Driver/src

# C source files

SOURCES += $(BOOTLOADER_SOURCES_DIR)/device/STM32F10x_StdPeriph_Driver/src/misc.c
SOURCES += $(BOOTLOADER_SOURCES_DIR)/device/STM32F10x_StdPeriph_Driver/src/stm32f10x_gpio.c
SOURCES += $(BOOTLOADER_SOURCES_DIR)/device/STM32F10x_StdPeriph_Driver/src/stm32f10x_bkp.c
SOURCES += $(BOOTLOADER_SOURCES_DIR)/device/STM32F10x_StdPeriph_Driver/src/stm32f10x_rcc.c
SOURCES += $(BOOTLOADER_SOURCES_DIR)/device/STM32F10x_StdPeriph_Driver/src/stm32f10x_can.c
SOURCES += $(BOOTLOADER_SOURCES_DIR)/device/STM32F10x_StdPeriph_Driver/src/stm32f10x_cec.c
SOURCES += $(BOOTLOADER_SOURCES_DIR)/device/STM32F10x_StdPeriph_Driver/src/stm32f10x_wwdg.c
SOURCES += $(BOOTLOADER_SOURCES_DIR)/device/STM32F10x_StdPeriph_Driver/src/stm32f10x_dbgmcu.c
SOURCES += $(BOOTLOADER_SOURCES_DIR)/device/STM32F10x_StdPeriph_Driver/src/stm32f10x_sdio.c
SOURCES += $(BOOTLOADER_SOURCES_DIR)/device/STM32F10x_StdPeriph_Driver/src/stm32f10x_fsmc.c
SOURCES += $(BOOTLOADER_SOURCES_DIR)/device/STM32F10x_StdPeriph_Driver/src/stm32f10x_crc.c
SOURCES += $(BOOTLOADER_SOURCES_DIR)/device/STM32F10x_StdPeriph_Driver/src/stm32f10x_dma.c
SOURCES += $(BOOTLOADER_SOURCES_DIR)/device/STM32F10x_StdPeriph_Driver/src/stm32f10x_spi.c
SOURCES += $(BOOTLOADER_SOURCES_DIR)/device/STM32F10x_StdPeriph_Driver/src/stm32f10x_exti.c
SOURCES += $(BOOTLOADER_SOURCES_DIR)/device/STM32F10x_StdPeriph_Driver/src/stm32f10x_tim.c
SOURCES += $(BOOTLOADER_SOURCES_DIR)/device/STM32F10x_StdPeriph_Driver/src/stm32f10x_adc.c
SOURCES += $(BOOTLOADER_SOURCES_DIR)/device/STM32F10x_StdPeriph_Driver/src/stm32f10x_rtc.c
SOURCES += $(BOOTLOADER_SOURCES_DIR)/device/STM32F10x_StdPeriph_Driver/src/stm32f10x_pwr.c
SOURCES += $(BOOTLOADER_SOURCES_DIR)/device/STM32F10x_StdPeriph_Driver/src/stm32f10x_flash.c
SOURCES += $(BOOTLOADER_SOURCES_DIR)/device/STM32F10x_StdPeriph_Driver/src/stm32f10x_iwdg.c
SOURCES += $(BOOTLOADER_SOURCES_DIR)/device/STM32F10x_StdPeriph_Driver/src/stm32f10x_dac.c
SOURCES += $(BOOTLOADER_SOURCES_DIR)/device/STM32F10x_StdPeriph_Driver/src/stm32f10x_i2c.c
SOURCES += $(BOOTLOADER_SOURCES_DIR)/device/STM32F10x_StdPeriph_Driver/src/stm32f10x_usart.c
